### ISSUE TITLE
Styles being injected into liquid-container

### ISSUE THREAD

**Issue by scolyer** [ef4/liquid-fire#330]
I'm having some problems getting an element I am centering on the screen to play well with liquid-fire.
```css
#myElement {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
```
I'm overriding liquid-container's styles with this rule:

```css
.liquid-container
{
    transform: initial;
}
```

Which works until I run a toLeft transition and then return to my login element via toRight.  The problem appears to be liquid-child, which is getting some styles injected:

```html
<div id="ember669" class="ember-view liquid-child" style="visibility: visible; top: 0px; left: 0px; transform: translateX(0px);">
      ...
</div>
```
Is there a way to turn this off, or do I need to tell my route to scrub the style attribute when it is loaded? Or is there another work-around?
