### ISSUE TITLE
Unable to do a simple fade with no movement

### ISSUE THREAD

**Issue by jdhines** [ef4/liquid-fire#359]
Of course, I might be doing this wrong, but I'm trying to make a simple "please save/changes saved" alert that I just want to fade in, but currently it's moving in from a little lower than its final place while fading in. 

I've made sure that the transition map is working, but that said, it may not be doing what I think it's doing.

*My markup*

````handlebars
{{#liquid-if model.isDirty class="save-alert save-alert-inline"}}
  <span class="text-danger"> Don't forget to save your changes!</span>
{{/liquid-if}}
````

*The transition map*

````javascript
export default function(){

  this.transition(
    this.hasClass('save-alert'),
    this.use('fade')
  );

  this.transition(
    this.fromRoute('budget.project-budget'),
    this.toRoute('budget.resource-budget'),
    this.use('toLeft'),
    this.reverse('toRight')
  );

  this.transition(
    this.hasClass('show-when-dirty'),
    this.use('toUp')
  );
}
````

*My CSS (had to override `overflow` because I wanted the liquid-container to be inline next to my save button)*

````css
.liquid-container.save-alert-inline {
  display: inline-block;
  overflow: visible;

  .liquid-child {
    overflow: visible
  }
  span {
    padding: 6px 12px;
    line-height: 1;
  }
}
````
